/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedResumesRouteImport } from './routes/_authenticated/resumes'
import { Route as AuthenticatedRepliesRouteImport } from './routes/_authenticated/replies'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedResumeStudioIndexRouteImport } from './routes/_authenticated/resume-studio/index'
import { Route as ApiLatexCompileRouteImport } from './routes/api/latex/compile'
import { Route as AuthenticatedResumeStudioIdRouteImport } from './routes/_authenticated/resume-studio/$id'
import { Route as AuthenticatedRecipientsIdRouteImport } from './routes/_authenticated/recipients.$id'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'
import { Route as ApiPublicGmailCallbackRouteImport } from './routes/api/public/gmail/callback'
import { Route as ApiPublicTrackPdfTokenRouteImport } from './routes/api/public/track/pdf/$token'
import { Route as ApiPublicTrackOpenTokenRouteImport } from './routes/api/public/track/open/$token'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumesRoute = AuthenticatedResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepliesRoute = AuthenticatedRepliesRouteImport.update({
  id: '/replies',
  path: '/replies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeStudioIndexRoute =
  AuthenticatedResumeStudioIndexRouteImport.update({
    id: '/resume-studio/',
    path: '/resume-studio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiLatexCompileRoute = ApiLatexCompileRouteImport.update({
  id: '/api/latex/compile',
  path: '/api/latex/compile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResumeStudioIdRoute =
  AuthenticatedResumeStudioIdRouteImport.update({
    id: '/resume-studio/$id',
    path: '/resume-studio/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipientsIdRoute =
  AuthenticatedRecipientsIdRouteImport.update({
    id: '/recipients/$id',
    path: '/recipients/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicGmailCallbackRoute = ApiPublicGmailCallbackRouteImport.update({
  id: '/api/public/gmail/callback',
  path: '/api/public/gmail/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackPdfTokenRoute = ApiPublicTrackPdfTokenRouteImport.update({
  id: '/api/public/track/pdf/$token',
  path: '/api/public/track/pdf/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackOpenTokenRoute = ApiPublicTrackOpenTokenRouteImport.update({
  id: '/api/public/track/open/$token',
  path: '/api/public/track/open/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/replies': typeof AuthenticatedRepliesRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/send': typeof AuthenticatedSendRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/recipients/$id': typeof AuthenticatedRecipientsIdRoute
  '/resume-studio/$id': typeof AuthenticatedResumeStudioIdRoute
  '/api/latex/compile': typeof ApiLatexCompileRoute
  '/resume-studio/': typeof AuthenticatedResumeStudioIndexRoute
  '/api/public/gmail/callback': typeof ApiPublicGmailCallbackRoute
  '/api/public/track/open/$token': typeof ApiPublicTrackOpenTokenRoute
  '/api/public/track/pdf/$token': typeof ApiPublicTrackPdfTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/replies': typeof AuthenticatedRepliesRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/send': typeof AuthenticatedSendRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/recipients/$id': typeof AuthenticatedRecipientsIdRoute
  '/resume-studio/$id': typeof AuthenticatedResumeStudioIdRoute
  '/api/latex/compile': typeof ApiLatexCompileRoute
  '/resume-studio': typeof AuthenticatedResumeStudioIndexRoute
  '/api/public/gmail/callback': typeof ApiPublicGmailCallbackRoute
  '/api/public/track/open/$token': typeof ApiPublicTrackOpenTokenRoute
  '/api/public/track/pdf/$token': typeof ApiPublicTrackPdfTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/replies': typeof AuthenticatedRepliesRoute
  '/_authenticated/resumes': typeof AuthenticatedResumesRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/recipients/$id': typeof AuthenticatedRecipientsIdRoute
  '/_authenticated/resume-studio/$id': typeof AuthenticatedResumeStudioIdRoute
  '/api/latex/compile': typeof ApiLatexCompileRoute
  '/_authenticated/resume-studio/': typeof AuthenticatedResumeStudioIndexRoute
  '/api/public/gmail/callback': typeof ApiPublicGmailCallbackRoute
  '/api/public/track/open/$token': typeof ApiPublicTrackOpenTokenRoute
  '/api/public/track/pdf/$token': typeof ApiPublicTrackPdfTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/dashboard'
    | '/followups'
    | '/history'
    | '/jobs'
    | '/notifications'
    | '/profile'
    | '/replies'
    | '/resumes'
    | '/send'
    | '/settings'
    | '/templates'
    | '/campaigns/$id'
    | '/recipients/$id'
    | '/resume-studio/$id'
    | '/api/latex/compile'
    | '/resume-studio/'
    | '/api/public/gmail/callback'
    | '/api/public/track/open/$token'
    | '/api/public/track/pdf/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/dashboard'
    | '/followups'
    | '/history'
    | '/jobs'
    | '/notifications'
    | '/profile'
    | '/replies'
    | '/resumes'
    | '/send'
    | '/settings'
    | '/templates'
    | '/campaigns/$id'
    | '/recipients/$id'
    | '/resume-studio/$id'
    | '/api/latex/compile'
    | '/resume-studio'
    | '/api/public/gmail/callback'
    | '/api/public/track/open/$token'
    | '/api/public/track/pdf/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/followups'
    | '/_authenticated/history'
    | '/_authenticated/jobs'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/replies'
    | '/_authenticated/resumes'
    | '/_authenticated/send'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/recipients/$id'
    | '/_authenticated/resume-studio/$id'
    | '/api/latex/compile'
    | '/_authenticated/resume-studio/'
    | '/api/public/gmail/callback'
    | '/api/public/track/open/$token'
    | '/api/public/track/pdf/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiLatexCompileRoute: typeof ApiLatexCompileRoute
  ApiPublicGmailCallbackRoute: typeof ApiPublicGmailCallbackRoute
  ApiPublicTrackOpenTokenRoute: typeof ApiPublicTrackOpenTokenRoute
  ApiPublicTrackPdfTokenRoute: typeof ApiPublicTrackPdfTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes': {
      id: '/_authenticated/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AuthenticatedResumesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/replies': {
      id: '/_authenticated/replies'
      path: '/replies'
      fullPath: '/replies'
      preLoaderRoute: typeof AuthenticatedRepliesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume-studio/': {
      id: '/_authenticated/resume-studio/'
      path: '/resume-studio'
      fullPath: '/resume-studio/'
      preLoaderRoute: typeof AuthenticatedResumeStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/latex/compile': {
      id: '/api/latex/compile'
      path: '/api/latex/compile'
      fullPath: '/api/latex/compile'
      preLoaderRoute: typeof ApiLatexCompileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resume-studio/$id': {
      id: '/_authenticated/resume-studio/$id'
      path: '/resume-studio/$id'
      fullPath: '/resume-studio/$id'
      preLoaderRoute: typeof AuthenticatedResumeStudioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipients/$id': {
      id: '/_authenticated/recipients/$id'
      path: '/recipients/$id'
      fullPath: '/recipients/$id'
      preLoaderRoute: typeof AuthenticatedRecipientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/gmail/callback': {
      id: '/api/public/gmail/callback'
      path: '/api/public/gmail/callback'
      fullPath: '/api/public/gmail/callback'
      preLoaderRoute: typeof ApiPublicGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/pdf/$token': {
      id: '/api/public/track/pdf/$token'
      path: '/api/public/track/pdf/$token'
      fullPath: '/api/public/track/pdf/$token'
      preLoaderRoute: typeof ApiPublicTrackPdfTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/open/$token': {
      id: '/api/public/track/open/$token'
      path: '/api/public/track/open/$token'
      fullPath: '/api/public/track/open/$token'
      preLoaderRoute: typeof ApiPublicTrackOpenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRepliesRoute: typeof AuthenticatedRepliesRoute
  AuthenticatedResumesRoute: typeof AuthenticatedResumesRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedRecipientsIdRoute: typeof AuthenticatedRecipientsIdRoute
  AuthenticatedResumeStudioIdRoute: typeof AuthenticatedResumeStudioIdRoute
  AuthenticatedResumeStudioIndexRoute: typeof AuthenticatedResumeStudioIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRepliesRoute: AuthenticatedRepliesRoute,
  AuthenticatedResumesRoute: AuthenticatedResumesRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  AuthenticatedRecipientsIdRoute: AuthenticatedRecipientsIdRoute,
  AuthenticatedResumeStudioIdRoute: AuthenticatedResumeStudioIdRoute,
  AuthenticatedResumeStudioIndexRoute: AuthenticatedResumeStudioIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiLatexCompileRoute: ApiLatexCompileRoute,
  ApiPublicGmailCallbackRoute: ApiPublicGmailCallbackRoute,
  ApiPublicTrackOpenTokenRoute: ApiPublicTrackOpenTokenRoute,
  ApiPublicTrackPdfTokenRoute: ApiPublicTrackPdfTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
